name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Remove Git folders from distribution
        run: rm -rf .git*
      - name: Install Dependencies
        run: npm install --prefix functions
      - name: Make envfile
        run: |
          touch functions/.env
#          echo RAPIDAPI_KEY=${{ secrets.RAPIDAPI_KEY }} >> functions/.env
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: .
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  post_deploy:
    name: Post Deploy
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Start Clear artifact
        run: |
          mkdir empty.d
      - name: Clear artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: empty.d
